[tool.pytest.ini_options]
addopts = "-v"

[tool.ruff]
target-version = "py38"
extend = "ruff_defaults.toml"



[tool.ruff.lint]

unfixable = [
    "F401", # unused imports
    "F841", # unused variables
]

[[tool.mypy.overrides]]
module = ["qgis.*", "osgeo.*"]
ignore_missing_imports = true
