name: "Create release."

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  release:
    name: "Release on tag"
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
